### ISSUE TITLE
Zeitlich abhängige Prüfungen – Stationäre Pflege

### ISSUE THREAD

**Issue by connexiadev** [connexiadev/Vodamep#10]
## Beschreibung
- Auflistung der zeitlich abhängigen Prüfungen bei der stationären Pflege
- Dient als Entscheidungsgrundlage für den Aufbau der Datenpakete
- Neben den zeitlichen Prüfungen gibt es zeitlich unabhängige Prüfungen, bei denen die entsprechende Meldung für die gesamte Validierung ausreicht
    - Z.B. Ist Feld x befüllt, wenn Feld y den Wert A hat
    - Diese Prüfungen sind hier nicht erwähnt

- Berücksichtig der Abhängigkeiten zwischen einzelnen Meldungen oder Aufenthalten

### Begriffe

- Aufnahme - Admission
- Aufenthalt – Stay
- Beendigung - Leaving

## PRÜFUNGEN ÜBER EINEN AUFENTHALT HINWEG

- Relevant, wenn ein Aufenthalt über mehrere Datenmeldungen verteilt gemeldet wird

### Aufnahme / Beendigung

- Ist pro Aufenthalt ein Aufnahmedatensatz vorhanden
- Ist pro Aufenthalt nur 1 Aufnahmedatensatz vorhanden
- Ist für einen beendeten Aufenthalt ein Beendigungsdatensatz vorhanden
- Ist für einen beendeten Aufenthalt nur 1 Beendigungsdatensatz vorhanden

### Durchgängigkeit

- Ist ein Aufenthalt bei einer über mehrere Pakete verteilte Aufenthaltsmeldung (Jahresmeldung. Monatsmeldung) durchgängig

### Attribute

- Hat sich bei Attributänderungen (Pflegestufe, Pflegestufe ARGE, Finanzierung) der Wert zur vorherigen Meldung geändert

### Überschneidungen Zeitbereich Aufenthalte

- Überschneiden sich keine Zeitbereiche der Aufenthalte für eine Person

### Aufenthalt

- Ist kein vorheriger Aufenthalt vorhanden, der mit Verstorben beendet wurde.
- Erfolgt kein Wechsel der Aufnahmeart von Daueraufnahme auf Urlaub, Probe oder Übergang
- Wurde die Dauer für eine zeitlich limitierte Pflege (Aufnahmeart) nicht überschritten (Urlaub 42 Tage, Probe 182 Tage, Übergang 365 Tage)

### Personendaten

- Stimmt das Geschlecht über mehrere Aufenthalte überein
- Stimmt das Geburtsdatum für eine Klienten ID über mehrere Aufenthalte überein
- Stimmt der Name für eine Klienten ID über mehrere Aufenthalte überein

**Comment by martbader** [comment]
Vorschlag von Leitprinzipien für den Paketinhalt:

- alle Daten der Aufenthalte im Meldezeitraum
- Jahresmeldung (monatlich gesendet)
- zwei angrenzende Meldungen müssen zueinander passen

**Comment by connexia-age** [comment]
Das Paket wurde umgebaut. Dieser Issue ist nicht mehr relevant.
