### ISSUE TITLE
Staatsbürgerschaft oder Land

### ISSUE THREAD

**Issue by martbader** [connexiadev/Vodamep#11]
In `Hkpv.proto` gibt es ein Feld `nationality`, das als Staatsbürgerschaft beschrieben ist.
In `Mohi.proto` gibt es das Feld `country`, welches vermutlich das Land der Adresse (`postcode`, `city`) meint und nicht die Staatsbürgerschaft?
In `StatLp.proto` gibt es auch das Feld `country`. In der bisherigen stationären Meldung gibt es auch das Feld Staatsangehörigkeit.
Meine Fragen:

- Gibt es die Staatsbürgerschaft nur noch bei Hkpv, sonst in keiner Meldung mehr? Beziehen sich alle anderen `country`-Felder auf den Wohnort?
- Wenn ja, wäre dann in `StatLp.proto` die Bezeichnung `last_country` ev. besser? (passend zu den Felder der vorherigen Adresse)

**Comment by connexiadev** [comment]
- Das ISO Kennzeichen wird ausschließlich für Staatsangehörigkeit verwendet, nie für den Wohnort.
- Bei StatLP kann man über last_country diskutieren, weil es den Aufnahme Zeitpunkt darstellt. Muss aber nicht sein.
- nationality wäre der bessere, klarere Begriff bei allen Schnittstellen. Da müssen wir aber schnell ändern, bevor TB Daten gesendet werden.


Hkpv   | Person    |   nationality    |   Staatsangehörigkeit
StatLP | Aufnahme  |   country        |   Staatsangehörigkeit
Mohi   | Person    |   country        |   Staatsangehörigkeit
Tb       | Person    |   country        |   Staatsangehörigkeit
Cm      | Person    |   country        |   Staatsangehörigkeit
Agp     | -
Mkkp  | -

**Comment by connexia-age** [comment]
- Das ISO Kennzeichen wird ausschließlich für Staatsangehörigkeit verwendet, nie für den Wohnort.
- Bei StatLP kann man über last_country diskutieren, weil es den Aufnahme Zeitpunkt darstellt. Muss aber nicht sein.
- nationality wäre der bessere, klarere Begriff bei allen Schnittstellen. Da müssen wir aber schnell ändern, bevor TB Daten gesendet werden.


Hkpv | Person | nationality | Staatsangehörigkeit
StatLP | Aufnahme | country | Staatsangehörigkeit
Mohi | Person | country | Staatsangehörigkeit
Tb | Person | country | Staatsangehörigkeit
Cm | Person | country | Staatsangehörigkeit
Agp | -
Mkkp | -

**Comment by martbader** [comment]
Wenn es immer die Staatsangehörigkeit ist, fände ich gut, wenn es immer `nationality ` heißt.
