### ISSUE TITLE
Unbekannte Staatsbürgerschaft

### ISSUE THREAD

**Issue by martbader** [connexiadev/Vodamep#12]
Ich kennen Fälle von Klienten, deren Staatsbürgerschaft nicht geklärt ist. ZB. Asylwerber, staatenlose Personen oder wenn sich die Staatsbürgerschaft nicht herausfinden lässt. 
In der Länderliste gibt es einen Eintrag `ZZ;Unbekannt`. Allerdings gilt dieser Eintrag laut Validatoren als Fehler.
Wie sollen Personen mit unbekannter Staatsbürgerschaft gesendet werden?

**Comment by connexia-age** [comment]
Nach gemeinsamer Abstimmung: 

- ZZ wird in Zukunft für alle Schnittstellen als gültiger Wert eingebaut
- Eine daraus resultierende mögliche Nicht-Erfassung des Lands wird über die Auswertungen geprüft
