### ISSUE TITLE
StatLp - Enum Änderungen

### ISSUE THREAD

**Issue by connexia-age** [connexiadev/Vodamep#20]
**Enum Änderung**
 - Bei der neuen Implementierung wurde der Enum CareAllowance abgeändert
 - Ursprünglicher Wert: UNDEFINED_ALLOWANCE
 - Neuer Wert: CARE_ALLOWANCE_UNSPECIFIED
 - Der Enum stammt schon aus der Zeit der HKPV

**Enum Verwendung**
- Der Enum wird zwischen allen Schnittstellen "geteilt"
- Der Enum wird auch in allen Schnittstellen verwenden
- Wie auch Gender, u.a.

**Vorteil**
- Beim Zusammenführen der Daten (z.B. für das Land) über alle Schnittstellen hinweg, werden die gleichen Werte übermittelt

Ich sehe die Vorteile von Unspecified.
Eine Umstellung zum jetzigen Zeitpunkt ist nur mit erheblichem Aufwand möglich.
Alle Schnittstellenpartner müssen ihre Schnittstellen anpassen.

Ich möchte das derzeit nicht anpassen.

**Comment by dgorbach** [comment]
Ok. Ich dachte das wäre kein Problem, weil die Werte als Zahl übermittelt werden. Der Aufwand für die Schnittstellenpartner wäre überschaubar.
Könntest du das wieder rückgängig machen?
