### ISSUE TITLE
StatLp - Aufenthaltswechsel zum Jahresende 

### ISSUE THREAD

**Issue by connexia-age** [connexiadev/Vodamep#21]
**Situation**
- Person mit Aufenthaltswechsel am 31.12.
- Wechsel soll von Urlaub auf Dauer erfolgen
- Entlassung somit nicht notwendig

**Meldung**
- Für die Entlassung am '31.12.2010' von 'Mustermann Max' wurden keine Entlassungsdaten gemeldet.

Übersehe ich da was?

Json im Anhang
[1.zip](https://github.com/connexiadev/Vodamep/files/7974404/1.zip)

**Comment by dgorbach** [comment]
Stimmt. Das werde ich ändern.
