### ISSUE TITLE
StatLp - Attributänderungen ohne Stay

### ISSUE THREAD

**Issue by connexia-age** [connexiadev/Vodamep#22]
**Situation**
- Aufenthalt mit Ende im gleichen Jahr
- Attributänderungen außerhalb des Aufenthaltszeitraums

Soll es erlaubt sein?
Derzeit geht das

JSON im Anhang
[1.zip](https://github.com/connexiadev/Vodamep/files/7974425/1.zip)

**Comment by dgorbach** [comment]
Aus meiner Sicht kann man das so lassen. Die Änderung betrifft den Meldezeitraum.

**Comment by connexia-age** [comment]
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/39065468/156044869-ccfcf8b3-2ae1-4e53-8b6a-511ab1ca75bb.png">

**Comment by dgorbach** [comment]
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/5755074/156128508-aa302e29-9394-4672-aef1-93cdf68b34ee.png">
 Ich würde Attribute nicht als Kästchen zeichnen.  Sie sind einer Person zugeordnet und sind nicht abhängig von einem Aufenthalt.

**Comment by connexia-age** [comment]
Wir haben das Thema bei connexia diskutiert. Folgende Argumente sprechen aus unserer Sicht gegen die Änderungen der Werte außerhalb der Aufenthalte:

- Pflegestufe ARGE ist heimbezogen, sie kann ohne einen Aufenthalt nicht festgelegt werden oder sich ändern.
- Finanzierung bezieht sich immer auf den Aufenthalt, der finanziert ist. Wenn die Person keinen Aufenthalt hat, stellt sich die Frage der Finanzierung des Aufenthalts nicht.
- Auch das Pflegegeld bezieht sich aus Sicht von connexia ebenfalls nur auf den Aufenthalt.

- Connexia ist ausschließlich berechtigt personenbezogene Daten zu erfassen und halten, die sich auf einen Aufenthalt beziehen.


Wir möchten das aber gerne in unserem nächsten Termin mitnehmen, wenn das für euch passt.

**Comment by connexia-age** [comment]
Nach gemeinsamer Abstimmung:

Attribut Änderungen außerhalb des Aufenthalts sollen nicht mehr möglich sein.
