### ISSUE TITLE
Validate von 2 Meldungen

### ISSUE THREAD

**Issue by connexia-age** [connexiadev/Vodamep#25]
**Stay von 2006**
```
    {
      "personId": "1234",
      "from": "2006-12-30T00:00:00Z",
      "type": "CONTINUOUS_AT"
    }
```

**Stay von 2007**
```
    {
      "personId": "1234",
      "from": "2006-12-30T00:00:00Z",
      "to": "2007-03-27T00:00:00Z",
      "type": "CONTINUOUS_AT"
    }
```

**Fehler**
Aufenthalte von 'Max Mustermann' stimmen nicht mit der vorhergehenden Meldung überein.

**Testaufruf**
Ich hab dafür eine Testmethode angelegt, mit dem 2 Reports geprüft werden können.
Wäre das etwa so vorgesehen gewesen?

`dmc validateprevious -f " D:\Data\2.json" -p "D:\Data\1.json" -t "StatLp"`

Stimmt da mit den Daten was nicht?
Jsons anbei.
[1.zip](https://github.com/connexiadev/Vodamep/files/7981564/1.zip)

**Comment by dgorbach** [comment]
Ich denke, das liegt eher am Validator. Nachdem ich nicht wusste, ob die Überarbeitung so angenommen wird, hab ich beim Validator und den Tests noch einige Fälle nicht beachtet.
Ich werde mir diesen Fall bald mal ansehen.
