### ISSUE TITLE
AGP Wegzeiten Prüfungsfehler

### ISSUE THREAD

**Issue by martbader** [connexiadev/Vodamep#40]
Validierungsfehler "Summe Wegzeiten ... darf 5 Stunden nicht überschreiten" scheint sich auf die Gesamtzeit, statt nur die Wegzeit zu beziehen. Für die Gesamtzeit sind 5 Stunden zu wenig, falls jemand länger arbeitet.

**Comment by connexia-age** [comment]
Dieses Problem kann ich so nicht nachstellen. 
Mit der aktuellen Version? 
Gibt es ein Beispiel Json?

Apropos: Es gibt jetzt eine neue Version, da sind schon die Namen + Staatsbürgerschaft drinnen.

**Comment by dgorbach** [comment]
Ich hab eine Unit-Test geschrieben der das Verhalten aufzeigt.

**Comment by connexia-age** [comment]
Danke für den Test!
