### ISSUE TITLE
AdmissionType zum Stay

### ISSUE THREAD

**Issue by dgorbach** [connexiadev/Vodamep#6]
Ich denke wir sollten die AdmissionType  (Aufnahmeart) zum Stay (Aufenthalt) geben. 

```
// Aufenthalt in der Einrichtung
message Stay {
    string person_id = 1;
    google.protobuf.Timestamp from = 2;
    google.protobuf.Timestamp to = 3;

    AdmissionType type = 4;
}
```

Ich denke, dass AdmissionType anders ist als die Pflegestufe, Finanzierung etc.

- Eine Person kann keine Aufnahmeart ohne Aufenthalt haben.
- Für die Validierung benötigt man Informationen über den Meldezeitraum hinaus. (z.B. die Gesamtdauer der Übergangspflege etc.)
- Es kann/muss genau definiert werden, was gemeldet werden soll. (Ein Aufenthalt war im vorletzten Meldezeitraum erst A, im letzten Meldezeitraum erfolgte ein Wechsel auf B. Im aktuellen Meldezeitraum ist er immer noch B). Welcher Wert soll in der aktuellen Meldung beim Stay für das From stehen? Ich denke es sollte das from vom Aufenthalt B gefordert werden. Dieser Wert sollte dann auch gegenüber der Meldung des letzten Meldezeitraumes validiert werden. Eventuell könnte man auch sagen A oder B. Oder mindestens B.

**Comment by connexia-age** [comment]
Ich denke auch, dass der AdmissionType zum Stay gehört.

**Comment by connexia-age** [comment]
Ich habe für den 3. Punkt einen eigenen Issue erstellt.
[](https://github.com/connexiadev/Vodamep/issues/7)

**Comment by dgorbach** [comment]
Passt
