### ISSUE TITLE
Dateiname bei StatLp anpassen

### ISSUE THREAD

**Issue by martbader** [connexiadev/Vodamep#69]
Im Unterschied zu den anderen Meldungstypen liefert, StatLp die Daten von 1.1. bis zum Monat, der gesendet wird.
Beim Schreiben der Daten in eine Datei wird der Dateiname in `ReportFilenameHandler` so bestimmt:
`var filename = $"{report.Institution.Id}_{report.FromD.Year}_{report.FromD.Month.ToString("00")}";`
Mein Vorschlag wäre, statt `FromD` jeweils `ToD` zu verwenden.
Für alle monatlichen Meldungen bleibt die Bezeichnung dieselbe. Für die StatLp wäre der Monat dann aber passend zum gesendeten Monat.

**Comment by connexia-age** [comment]
#78
