### ISSUE TITLE
Dateninhalt zur Person oder Stay

### ISSUE THREAD

**Issue by connexia-age** [connexiadev/Vodamep#7]
Wir haben uns heute noch gefragt, welche Daten in welchem Paket erfasst werden:

**Möglichkeit 1:** 
•	Nur jene aus dem aktuellen Meldungszeitraum
•	Z.B. ist eine Aufnahme vom Vorjahr ist also in der Meldung des Vorjahrs
•	Somit sind auch Attributänderungen nur aus dem aktuellen Jahr in der Meldung vorhanden

![image](https://user-images.githubusercontent.com/39065468/142458451-405c208d-75a3-4e95-b40a-9840b8f51436.png)

 
Vorteil: 
•	Klare Abgrenzung zwischen den Paketen, die Wahrheit steckt jeweils nur in 1 Paket

Nachteil: 
•	Nur Teile vom Paket sind vollständig – jene, die sich vollständig im aktuellen Jahr abgespielt haben

**Möglichkeit 2:** 
•	Alle Daten zum Aufenthalt, bis zur letzten Lücke im Paket

![image](https://user-images.githubusercontent.com/39065468/142458407-cdeeff61-9480-4f60-8375-8cb581bcc43a.png)
 

Vorteil: 
•	Das Paket ist in sich vollständiger, aber auch nie ganz

Nachteil:
•	Ein Merge von 2 Jahresmeldungen muss entscheiden, ob die Wahrheit in Paket 1 oder 2 steckt
•	Abhängigkeiten zu Vorjahresmeldungen und Meldungen davor sind immer noch vorhanden und müssen geprüft werden
•	Diese Überschneidungen sind in SQL nicht wirklich gewünscht

**Möglichkeit 3:**
•	Wird ein Stay für eine Person im Jahr gemeldet, ist auch die gesamte Geschichte der Person mit der Einrichtung enthalten
 
![image](https://user-images.githubusercontent.com/39065468/142458320-a69ee731-a631-4d5a-ba6d-cc2068878943.png)

Vorteil: 
•	Die ganze Wahrheit steckt in der letzten Meldung der Person
•	Ein Paket ist immer vollständig konsistent

Nachteil: 
•	Große Datenpakete
•	Für die Aufenthaltsermittlung von 2 Jahren müssen trotzdem Personen, die im ältesten Paket vorhanden sind aus dem Paket davor entfernt werden

**Comment by dgorbach** [comment]
Ich versteh den Zusammenhang zwischem den Titel des Issues (Dateninhalt zur Person oder Stay) und dem Inhalt nicht ganz. 

Ich würde vorschlagen, den Titel auf etwas in der Art: 'Welche Daten/Zeiträume sollen im Stay gemeldet werden'.

Ich würde folgendes Vorschlagen:

Stay: von, bis, Aufnahmeart

Es werden nur Aufenthalte gemeldet, die den Meldezeitraum betreffen.

von-Datum
- Wenn eine Aufnahme im Meldezeitraum erfolgt, das Aufnahmedateum
- Wenn eine Wechsel der Aufnahmeart erfolt, das Datum des Wechsels
- Wenn die Aufnahme vor dem Meldezeitraum erfolgte, bleibt der Wert leer, es sei denn
- 	die Aufnahmeart ist Urlaubsbetreuung oder Übergangspflege. In diesem Fall wird im von-Datum der Beginn dieser Aufnahme gemeldet.

bis-Datum
- Wenn eine Entlassung im Meldezeitrum erfolg, das Entlassungsdatum
- Wenn eine Wechsel der Aufnahmeart erfolt, das Datum des Wechsels (Achtung: Hier würde sich auch das Datum vor dem Tag des Wechsels anbieten. Wegen der besseren Überprüfbarkeit an den Grenzen der Meldezeiträume würde ich aber das Datum des Wechsels verwenden. Wenn jemand also ab 1.1 eine Aufnahmeart hat, dann braucht es zwei Einträge)
- Wenn sich nichts ändert, bleibt das bis-Datum leer

**Comment by dgorbach** [comment]
ad: 
_"Diese Überschneidungen sind in SQL nicht wirklich gewünscht."_

Ich lese da zwischen den Zeilen, dass die Datenpakete möglicherweise nicht die 'Single Source Of Truth' sind. Wenn die Inhalte der Datenpakete zusätzlich in eine relationalen Datenbank gehegt und gepflegt werden, würde ich anregen das zu hinterfragen. Weil komplex, aufwändig, teuer.

Sollte es notwendig sein, die Inhalte der Datenpakete in eine Relational Datenbank zu übernehmen, dann könnte man diese so füllen, dass man mit SQL kein Problem hat. Und anschließend verwirft man diese DB wieder.

**Comment by connexia-age** [comment]
Über den Titel kann man diskutieren. Die Frage, die wir uns gestellt haben ist aber eine andere:

Stay der Person: Vom 30.06.2019 bis 31.12.2020, Daueraufnahme
Meldung, die gesendet wird: 31.12.2020

- Ist die Aufnahme vom 30.06.2019 im Paket vom 31.12.2020 enthalten?
- Sind z.B. Attributänderungen am 01.10.2019 vom Paket vom 31.12.2020 enthalten?

**Comment by connexia-age** [comment]
"Wenn die Inhalte der Datenpakete zusätzlich in eine relationalen Datenbank gehegt und **gepflegt** werden"

Gehegt werden sie, gepflegt nicht.

**Comment by dgorbach** [comment]
Ok, ich verstehe, es geht hier auch um die Attribute. Ich dachte es geht nur um die Meldung der Aufenthalte.

Für das Beispiel würde folgendes gemeldet werden:

Stay: from leer, to leer (oder wenn am 31.12.2020 die Entlassung erfolgt, 31.12.2020), Type: Daueraufname

Attribute:
- Unter Attribute verstehe ich PS, Finanzierung und ARGE
- Die Änderungen der Attribute außerhalb des Zeitraums sind nicht dabei. 
- Vermutlich notwendig wird sein, dass zu jedem Zeitpunkt eines Aufenthaltes die Attribute definiert sein müssen. In diesen Fall würde die PS, Finanzierung, etc. dann jeweils zum Beginn des Meldezeitraums gemeldet werden.

Im Datenpaket nicht vorhanden wären die Daten zur Aufnahme, weil die Aufnahme außerhalb des Meldezeitraums erfolgte.

**Comment by connexia-age** [comment]
So haben wir uns das auch gedacht. Super!

Bis auf diesen Punkt:

- Vermutlich notwendig wird sein, dass zu jedem Zeitpunkt eines Aufenthaltes die Attribute definiert sein müssen. In diesen Fall würde die PS, Finanzierung, etc. dann jeweils zum Beginn des Meldezeitraums gemeldet werden.

Würde das bedeuten, dass für unser Bespiel in der Meldung vom 31.12.2020 eine Attribute-Definition mit 01.01.2020 dabei ist.
Aus meiner Sicht ist das nicht notwendig, da der Stay der Person ja auch nicht vollständig ist und ohne Vormeldung nicht gesamthaft geprüft werden kann.

Beispiel: In der Meldung vom 31.12.2019 ein Stay vom Typ "Daueraufnahme" mit Start 01.12.2019, in der nächsten Meldung vom 31.01.2020 ein Wechsel auf "Urlaub" am 05.01.2021 -> geht nicht

**Comment by dgorbach** [comment]
Wir reden hier von zwei Arten von Daten. Einerseits Attribute (Pflegestufe, Finanzierung, ARGE) und andererseits Stay (Aufnahmeart)

Die Werte in Attribute können nicht wirklich validiert werden. Da kann nur verlangt werden, dass sie vorhanden sind. Und die sollten (denk ich) für den Meldezeitraum vollständig vorhanden sein, weil es da ja Auswertungen gibt. Z.B. Wie viele Belegungstage pro Pflegestufe etc.

Die Aufnahmeart im Stay muss validiert werden. Ich kenne die Regeln nicht auswendig, aber es gibt da z.B. eine maximale Dauer für "Urlaub". Vielleicht geht es auch nicht, dass auf "Daueraufname" ein "Urlaub" folgt. etc. Alle Daten, die es für eine solche Validierung braucht, sollten in einem Paket vorhanden sein.

Was dann noch zusätzlich validiert werden muss ist, ob zwei angrenzende Pakete zueinander passen. (wenn "from" im Stay eines Klienten leer ist, muss im Pakte davor der Klient ein Stay haben, dessen "to" leer ist.)

Wenn man eine Jahresauswertung machen will, sollte es genügen, wenn nur die Pakete dieses Jahres herangezogen werden. Bei einem Meldezeitraum von einem Jahr, wäre das ein Paket pro Einrichtung.

**Comment by connexia-age** [comment]
Wir können diesen Punkt die Auswirkungen im Moment nicht vollständig beantworten. Ich würde die Auswertungen bei der Betrachtung weglassen, da sie nicht mit Vodamep durchgeführt werden. Wir schauen uns jetzt erst mal die Prüfungen an, die über mehrere Pakete hinweg vorkommen können und treffen dann die Entscheidung.
Für die Prüfungen machen wir einen neuen Issue auf.
