### ISSUE TITLE
Orte mit alternativer Schreibweise zulassen

### ISSUE THREAD

**Issue by martbader** [connexiadev/Vodamep#76]
Es gibt Orte, die verschieden geschrieben werden können. Z.B. "St. Anton im Montafon" oder "St. Gallenkirch" könnten auch das "St." ausgeschrieben mit "Sankt" haben. Davon gibt es noch mehrere Beispiele.
Es wäre praktisch, wenn beide bzw. mehrere Schreibweisen zulässig wären.

**Comment by connexia-age** [comment]
PLZ Liste wurde erweitert
