### ISSUE TITLE
Alt / Neu - PLZ + Ort

### ISSUE THREAD

**Issue by connexia-age** [connexiadev/Vodamep#8]
Das ist der Unterschied zwischen Alt / Neu. 

Zu klären ist die Frage, ob PLZ / Ort zur Person gehört.
Die Aussage hinter dem Feld ist "PLZ des letzten Wohnorts" - im Sinne von "vor der Aufnahme".

![image](https://user-images.githubusercontent.com/39065468/142459342-e39fa487-dac4-462b-aac4-8e64bc4f6d0d.png)

**Comment by dgorbach** [comment]
Ich würde das abhängig vom Bedarf machen. Es sollten alle für die Validierungen und Auswertungen relevanten Daten im Paket vorhanden sein.  Wenn es Jahresauswertungen gibt, aber Monatsmeldungen, dann sollte es genügen, die 12 Monatspakete auszuwerten. etc.

Nachdem es für die Validierung nicht relevant ist, stellt sich die Frage: Was benötigt man für die Auswertung?

**Comment by connexia-age** [comment]
Hier verstehe ich die Frage nicht ganz. Es geht nur um PLZ/Ort. 
Lt. aktueller Definitionen ist es nicht der aktuell gemeldete Wohnort, sondern der Wohnort, an dem die Person vor der Aufnahme in die Einrichtung gewohnt hat. 
Aus meiner Sicht gehört es zur Aufnahme. 
Anders verhält es sich dann aber z.B. bei der mobile Pflege. Da kann es durchaus der aktuelle Wohnort sein, der sich von Meldung zu Meldung ändert.

**Comment by dgorbach** [comment]
Passt gut, wenn es bei der den Aufnahmedaten dabei ist. Ich finden in den Daten zur Aufnahme sollen nur Daten sein, die Jahre nach der Aufnahme nicht mehr relevant sind. 

Angenommen eine Bewohnerin wohnt seit 10 Jahren im Pflegeheim. Welche Daten müssen im Heim noch gepflegt werden? 

Ich denke z.B. die Wohnform vor der Aufnahme kann nicht mehr relevant sein. 

Beim vorherigen Wohnort hatte ich die Vermutung, dass es da vielleicht noch irgendwelche Auswertungen geben muss.

**Comment by connexia-age** [comment]
Passt für uns gut!

**Comment by connexia-age** [comment]
Nachdem wir die Auswertungen nicht kennen und sich die Erfassung des letzten Wohnorts bei der Aufnahme stattfindet, passen die Daten besser zur Aufnahmen.

**Comment by connexia-age** [comment]
.
